[publish]
#publish id
publish_id=0

#publish type
#0: NAN_PUBLISH_SOLICITED   Send unicast Publish frame to Subscribers that match the requirement
#1: NAN_PUBLISH_UNSOLICITED Send broadcast Publish frames in every Discovery Window(DW)
publish_type=1

#service name, max len 32
service_name=nan_test

#service info, max len 255
service_specific_info=welcome to nan world!

#match_filter_tx <len,vlaue> pairs, max len+val 64
match_filter_tx=<2,1,1><1,2>

#match_filter_rx <len,vlaue> pairs, max len+val 64
match_filter_rx=<2,1,3>