/* SPDX-License-Identifier: GPL-2.0 */
/*
* Copyright (C) 202X Original Author (retain original author information)
* Copyright (C) 202X Amlogic, Inc. All rights reserved.
*
* Description:
*/
#ifndef __ADDR_INTF_H__
#define __ADDR_INTF_H__
// ----------------------------------------------------------------------
// This file is automatically generated from the script:
//
// $AMVE_HOME/bin/gen_reg/gen_reg.py
//
// and was applied to the file
//
// block name: wifi_inft_reg
//
// Create time: 2025-02-26 11:12:50.480804 by xiaolei.cheng
//
// DO NOT EDIT!!!!!
// ----------------------------------------------------------------------
//

#ifdef WIFI_INFT_REG
#else
#define WIFI_INFT_REG

#define WIFI_INFT_REG_BASE                        (0x00a0d000)

#define WF_AN_CFG                                 (0x00a0d018)

#define P_WF_AN_CFG                               (volatile uint32_t*)(0x00a0d018)

#define WF_AN_CFG_OS                              (0x00000018)

#define WF_AN_CFG_RESET                           (0x80)

// Bit 31  :0      reg_wf_an_cfg                  U     RW        default = 'h80
typedef union WF_AN_CFG_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_wf_an_cfg : 32;
  } b;
} WF_AN_CFG_FIELD_T;

#define REG_RAM_PD_SHUTDOWN_HW                    (0x00a0d028)

#define P_REG_RAM_PD_SHUTDOWN_HW                  (volatile uint32_t*)(0x00a0d028)

#define REG_RAM_PD_SHUTDOWN_HW_OS                 (0x00000028)

#define REG_RAM_PD_SHUTDOWN_HW_RESET              (0xffffffff)

// Bit 31  :0      reg_ram_pd_shutdown_hw         U     RW        default = 'hffffffff
typedef union REG_RAM_PD_SHUTDOWN_HW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_shutdown_hw : 32;
  } b;
} REG_RAM_PD_SHUTDOWN_HW_FIELD_T;

#define REG_RAM_PD_DISB_GATE_HW                   (0x00a0d02c)

#define P_REG_RAM_PD_DISB_GATE_HW                 (volatile uint32_t*)(0x00a0d02c)

#define REG_RAM_PD_DISB_GATE_HW_OS                (0x0000002c)

#define REG_RAM_PD_DISB_GATE_HW_RESET             (0xffffffff)

// Bit 31  :0      reg_ram_pd_disb_gate_hw        U     RW        default = 'hffffffff
typedef union REG_RAM_PD_DISB_GATE_HW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_disb_gate_hw : 32;
  } b;
} REG_RAM_PD_DISB_GATE_HW_FIELD_T;

#define REG_RAM_PD_SHUTDOWN_SW                    (0x00a0d030)

#define P_REG_RAM_PD_SHUTDOWN_SW                  (volatile uint32_t*)(0x00a0d030)

#define REG_RAM_PD_SHUTDOWN_SW_OS                 (0x00000030)

#define REG_RAM_PD_SHUTDOWN_SW_RESET              (0x0)

// Bit 31  :0      reg_ram_pd_shutdown_sw         U     RW        default = 'h0
typedef union REG_RAM_PD_SHUTDOWN_SW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_shutdown_sw : 32;
  } b;
} REG_RAM_PD_SHUTDOWN_SW_FIELD_T;

#define REG_RAM_PD_DISB_GATE_SW                   (0x00a0d034)

#define P_REG_RAM_PD_DISB_GATE_SW                 (volatile uint32_t*)(0x00a0d034)

#define REG_RAM_PD_DISB_GATE_SW_OS                (0x00000034)

#define REG_RAM_PD_DISB_GATE_SW_RESET             (0x0)

// Bit 31  :0      reg_ram_pd_disb_gate_sw        U     RW        default = 'h0
typedef union REG_RAM_PD_DISB_GATE_SW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_disb_gate_sw : 32;
  } b;
} REG_RAM_PD_DISB_GATE_SW_FIELD_T;

#define REG_RAM_PD_SEL0_SW                        (0x00a0d038)

#define P_REG_RAM_PD_SEL0_SW                      (volatile uint32_t*)(0x00a0d038)

#define REG_RAM_PD_SEL0_SW_OS                     (0x00000038)

#define REG_RAM_PD_SEL0_SW_RESET                  (0xffffffff)

// Bit 31  :0      reg_ram_pd_sel0_sw             U     RW        default = 'hffffffff
typedef union REG_RAM_PD_SEL0_SW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_sel0_sw : 32;
  } b;
} REG_RAM_PD_SEL0_SW_FIELD_T;

#define REG_RAM_PD_SEL1_SW                        (0x00a0d03c)

#define P_REG_RAM_PD_SEL1_SW                      (volatile uint32_t*)(0x00a0d03c)

#define REG_RAM_PD_SEL1_SW_OS                     (0x0000003c)

#define REG_RAM_PD_SEL1_SW_RESET                  (0x0)

// Bit 31  :0      reg_ram_pd_sel0_sw             U     RW        default = 'h0
typedef union REG_RAM_PD_SEL1_SW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_sel0_sw : 32;
  } b;
} REG_RAM_PD_SEL1_SW_FIELD_T;

#define REG_RAM_PD_SEL0_HW                        (0x00a0d040)

#define P_REG_RAM_PD_SEL0_HW                      (volatile uint32_t*)(0x00a0d040)

#define REG_RAM_PD_SEL0_HW_OS                     (0x00000040)

#define REG_RAM_PD_SEL0_HW_RESET                  (0xffffffff)

// Bit 31  :0      reg_ram_pd_sel0_hw             U     RW        default = 'hffffffff
typedef union REG_RAM_PD_SEL0_HW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_sel0_hw : 32;
  } b;
} REG_RAM_PD_SEL0_HW_FIELD_T;

#define REG_RAM_PD_SEL1_HW                        (0x00a0d044)

#define P_REG_RAM_PD_SEL1_HW                      (volatile uint32_t*)(0x00a0d044)

#define REG_RAM_PD_SEL1_HW_OS                     (0x00000044)

#define REG_RAM_PD_SEL1_HW_RESET                  (0xffffffff)

// Bit 31  :0      reg_ram_pd_sel0_hw             U     RW        default = 'hffffffff
typedef union REG_RAM_PD_SEL1_HW_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ram_pd_sel0_hw : 32;
  } b;
} REG_RAM_PD_SEL1_HW_FIELD_T;

#define MSR_CLK_CTRL0                             (0x00a0d048)

#define P_MSR_CLK_CTRL0                           (volatile uint32_t*)(0x00a0d048)

#define MSR_CLK_CTRL0_OS                          (0x00000048)

#define MSR_CLK_CTRL0_RESET                       (0x0)

// Bit 31  :0      msr_clk_ctrl0                  U     RO        default = 'h0
typedef union MSR_CLK_CTRL0_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int msr_clk_ctrl0 : 32;
  } b;
} MSR_CLK_CTRL0_FIELD_T;

#define MSR_CLK_CTRL1                             (0x00a0d04c)

#define P_MSR_CLK_CTRL1                           (volatile uint32_t*)(0x00a0d04c)

#define MSR_CLK_CTRL1_OS                          (0x0000004c)

#define MSR_CLK_CTRL1_RESET                       (0x0)

// Bit 30  :0      msr_clk_ctrl1                  U     RO        default = 'h0
// Bit 31          reg_msr_ctrl1                  U     RO        default = 'h0
typedef union MSR_CLK_CTRL1_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int msr_clk_ctrl1 : 31;
    unsigned int reg_msr_ctrl1 : 1;
  } b;
} MSR_CLK_CTRL1_FIELD_T;

#define MSR_CLK_CTRL2                             (0x00a0d050)

#define P_MSR_CLK_CTRL2                           (volatile uint32_t*)(0x00a0d050)

#define MSR_CLK_CTRL2_OS                          (0x00000050)

#define MSR_CLK_CTRL2_RESET                       (0x0)

// Bit 31  :0      measured_value                 U     RO        default = 'h0
typedef union MSR_CLK_CTRL2_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int measured_value : 32;
  } b;
} MSR_CLK_CTRL2_FIELD_T;

#define MSR_CLK_CTRL3                             (0x00a0d054)

#define P_MSR_CLK_CTRL3                           (volatile uint32_t*)(0x00a0d054)

#define MSR_CLK_CTRL3_OS                          (0x00000054)

#define MSR_CLK_CTRL3_RESET                       (0x0)

// Bit 31  :0      min_exp                        U     RW        default = 'h0
typedef union MSR_CLK_CTRL3_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int min_exp : 32;
  } b;
} MSR_CLK_CTRL3_FIELD_T;

#define MSR_CLK_CTRL4                             (0x00a0d058)

#define P_MSR_CLK_CTRL4                           (volatile uint32_t*)(0x00a0d058)

#define MSR_CLK_CTRL4_OS                          (0x00000058)

#define MSR_CLK_CTRL4_RESET                       (0x0)

// Bit 31  :0      max_exp                        U     RW        default = 'h0
typedef union MSR_CLK_CTRL4_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int max_exp : 32;
  } b;
} MSR_CLK_CTRL4_FIELD_T;

#define MSR_CLK_CTRL5                             (0x00a0d05c)

#define P_MSR_CLK_CTRL5                           (volatile uint32_t*)(0x00a0d05c)

#define MSR_CLK_CTRL5_OS                          (0x0000005c)

#define MSR_CLK_CTRL5_RESET                       (0x0)

// Bit 31  :0      start_p                        U     RW        default = 'h0
typedef union MSR_CLK_CTRL5_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int start_p : 32;
  } b;
} MSR_CLK_CTRL5_FIELD_T;

#define MSR_CLK_DUTY                              (0x00a0d060)

#define P_MSR_CLK_DUTY                            (volatile uint32_t*)(0x00a0d060)

#define MSR_CLK_DUTY_OS                           (0x00000060)

#define MSR_CLK_DUTY_RESET                        (0x0)

// Bit 15  :0      duty_cnt_low                   U     RO        default = 'h0
// Bit 31  :16     duty_cnt_high                  U     RO        default = 'h0
typedef union MSR_CLK_DUTY_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int duty_cnt_low : 16;
    unsigned int duty_cnt_high : 16;
  } b;
} MSR_CLK_DUTY_FIELD_T;

#define MSR_WF_HW_GRANT                           (0x00a0d070)

#define P_MSR_WF_HW_GRANT                         (volatile uint32_t*)(0x00a0d070)

#define MSR_WF_HW_GRANT_OS                        (0x00000070)

#define MSR_WF_HW_GRANT_RESET                     (0x1)

// Bit 0           reg_wf_hw_grant_sel            U     RW        default = 'h1
// Bit 1           reg_wf_hw_grant                U     RW        default = 'h0
typedef union MSR_WF_HW_GRANT_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_wf_hw_grant_sel : 1;
    unsigned int reg_wf_hw_grant : 1;
    unsigned int rsvd_0 : 30;
  } b;
} MSR_WF_HW_GRANT_FIELD_T;

#define CONTROL_MACWT_CLOCK                       (0x00a0d07c)

#define P_CONTROL_MACWT_CLOCK                     (volatile uint32_t*)(0x00a0d07c)

#define CONTROL_MACWT_CLOCK_OS                    (0x0000007c)

#define CONTROL_MACWT_CLOCK_RESET                 (0x10001)

// Bit 0           reg_macwt_clk_en               U     RW        default = 'h1
// Bit 4           reg_macwt_osc_sel              U     RW        default = 'h0
// Bit 19  :16     reg_macwt_clk_div              U     RW        default = 'h1
typedef union CONTROL_MACWT_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_macwt_clk_en : 1;
    unsigned int rsvd_0 : 3;
    unsigned int reg_macwt_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_macwt_clk_div : 4;
    unsigned int rsvd_2 : 12;
  } b;
} CONTROL_MACWT_CLOCK_FIELD_T;

#define CONTROL_MACCORE_CLOCK                     (0x00a0d080)

#define P_CONTROL_MACCORE_CLOCK                   (volatile uint32_t*)(0x00a0d080)

#define CONTROL_MACCORE_CLOCK_OS                  (0x00000080)

#define CONTROL_MACCORE_CLOCK_RESET               (0x10001)

// Bit 0           reg_maccore_clk_en             U     RW        default = 'h1
// Bit 4           reg_maccore_osc_sel            U     RW        default = 'h0
// Bit 20  :16     reg_maccore_clk_div            U     RW        default = 'h1
typedef union CONTROL_MACCORE_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_maccore_clk_en : 1;
    unsigned int rsvd_0 : 3;
    unsigned int reg_maccore_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_maccore_clk_div : 5;
    unsigned int rsvd_2 : 11;
  } b;
} CONTROL_MACCORE_CLOCK_FIELD_T;

#define CONTROL_MPIF_CLOCK                        (0x00a0d084)

#define P_CONTROL_MPIF_CLOCK                      (volatile uint32_t*)(0x00a0d084)

#define CONTROL_MPIF_CLOCK_OS                     (0x00000084)

#define CONTROL_MPIF_CLOCK_RESET                  (0x20001)

// Bit 0           reg_mpif_clk_en                U     RW        default = 'h1
// Bit 4           reg_mpif_osc_sel               U     RW        default = 'h0
// Bit 18  :16     reg_mpif_clk_div               U     RW        default = 'h2
typedef union CONTROL_MPIF_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_mpif_clk_en : 1;
    unsigned int rsvd_0 : 3;
    unsigned int reg_mpif_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_mpif_clk_div : 3;
    unsigned int rsvd_2 : 13;
  } b;
} CONTROL_MPIF_CLOCK_FIELD_T;

#define CONTROL_LDPCRX_CLOCK                      (0x00a0d088)

#define P_CONTROL_LDPCRX_CLOCK                    (volatile uint32_t*)(0x00a0d088)

#define CONTROL_LDPCRX_CLOCK_OS                   (0x00000088)

#define CONTROL_LDPCRX_CLOCK_RESET                (0x20001)

// Bit 0           reg_ldpcrx_clk_en              U     RW        default = 'h1
// Bit 4           reg_ldpcrx_osc_sel             U     RW        default = 'h0
// Bit 18  :16     reg_ldpcrx_clk_div             U     RW        default = 'h2
typedef union CONTROL_LDPCRX_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ldpcrx_clk_en : 1;
    unsigned int rsvd_0 : 3;
    unsigned int reg_ldpcrx_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_ldpcrx_clk_div : 3;
    unsigned int rsvd_2 : 13;
  } b;
} CONTROL_LDPCRX_CLOCK_FIELD_T;

#define CONTROL_VTB_CLOCK                         (0x00a0d08c)

#define P_CONTROL_VTB_CLOCK                       (volatile uint32_t*)(0x00a0d08c)

#define CONTROL_VTB_CLOCK_OS                      (0x0000008c)

#define CONTROL_VTB_CLOCK_RESET                   (0x20001)

// Bit 0           reg_vtb_clk_en                 U     RW        default = 'h1
// Bit 4           reg_vtb_osc_sel                U     RW        default = 'h0
// Bit 18  :16     reg_vtb_clk_div                U     RW        default = 'h2
typedef union CONTROL_VTB_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_vtb_clk_en : 1;
    unsigned int rsvd_0 : 3;
    unsigned int reg_vtb_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_vtb_clk_div : 3;
    unsigned int rsvd_2 : 13;
  } b;
} CONTROL_VTB_CLOCK_FIELD_T;

#define CONTROL_CPU_CLOCK                         (0x00a0d090)

#define P_CONTROL_CPU_CLOCK                       (volatile uint32_t*)(0x00a0d090)

#define CONTROL_CPU_CLOCK_OS                      (0x00000090)

#define CONTROL_CPU_CLOCK_RESET                   (0x4f210003)

// Bit 1   :0      reg_cpu_clk_en                 U     RW        default = 'h3
// Bit 11  :4      reg_cpu_osc_sel                U     RW        default = 'h0
// Bit 31  :16     reg_cpu_clk_div                U     RW        default = 'h4f21
typedef union CONTROL_CPU_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_cpu_clk_en : 2;
    unsigned int rsvd_0 : 2;
    unsigned int reg_cpu_osc_sel : 8;
    unsigned int rsvd_1 : 4;
    unsigned int reg_cpu_clk_div : 16;
  } b;
} CONTROL_CPU_CLOCK_FIELD_T;

#define CONTROL_PCIE_CLOCK                        (0x00a0d094)

#define P_CONTROL_PCIE_CLOCK                      (volatile uint32_t*)(0x00a0d094)

#define CONTROL_PCIE_CLOCK_OS                     (0x00000094)

#define CONTROL_PCIE_CLOCK_RESET                  (0x120003)

// Bit 1   :0      reg_pcie_clk_en                U     RW        default = 'h3
// Bit 11  :4      reg_pcie_osc_sel               U     RW        default = 'h0
// Bit 23  :16     reg_pcie_clk_div               U     RW        default = 'h12
typedef union CONTROL_PCIE_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_pcie_clk_en : 2;
    unsigned int rsvd_0 : 2;
    unsigned int reg_pcie_osc_sel : 8;
    unsigned int rsvd_1 : 4;
    unsigned int reg_pcie_clk_div : 8;
    unsigned int rsvd_2 : 8;
  } b;
} CONTROL_PCIE_CLOCK_FIELD_T;

#define CONTROL_DAC_CLOCK                         (0x00a0d0a0)

#define P_CONTROL_DAC_CLOCK                       (volatile uint32_t*)(0x00a0d0a0)

#define CONTROL_DAC_CLOCK_OS                      (0x000000a0)

#define CONTROL_DAC_CLOCK_RESET                   (0x3b5ed811)

// Bit 0           reg_dac_clk_en                 U     RW        default = 'h1
// Bit 1           reg_dac_clk_inv                U     RW        default = 'h0
// Bit 4           reg_dac_osc_sel                U     RW        default = 'h1
// Bit 31  :8      reg_dac_clk_div                U     RW        default = 'h3b5ed8
typedef union CONTROL_DAC_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_dac_clk_en : 1;
    unsigned int reg_dac_clk_inv : 1;
    unsigned int rsvd_0 : 2;
    unsigned int reg_dac_osc_sel : 1;
    unsigned int rsvd_1 : 3;
    unsigned int reg_dac_clk_div : 24;
  } b;
} CONTROL_DAC_CLOCK_FIELD_T;

#define CONTROL_ADC_CLOCK                         (0x00a0d0a4)

#define P_CONTROL_ADC_CLOCK                       (volatile uint32_t*)(0x00a0d0a4)

#define CONTROL_ADC_CLOCK_OS                      (0x000000a4)

#define CONTROL_ADC_CLOCK_RESET                   (0x8400011)

// Bit 0           reg_adc_clk_en                 U     RW        default = 'h1
// Bit 2   :1      reg_adc_clk_inv                U     RW        default = 'h0
// Bit 4           reg_adc_osc_sel                U     RW        default = 'h1
// Bit 27  :16     reg_adc_clk_div                U     RW        default = 'h840
typedef union CONTROL_ADC_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_adc_clk_en : 1;
    unsigned int reg_adc_clk_inv : 2;
    unsigned int rsvd_0 : 1;
    unsigned int reg_adc_osc_sel : 1;
    unsigned int rsvd_1 : 11;
    unsigned int reg_adc_clk_div : 12;
    unsigned int rsvd_2 : 4;
  } b;
} CONTROL_ADC_CLOCK_FIELD_T;

#define CONTROL_DAC_CLOCK_SEL                         (0x00a0d0a8)

#define P_CONTROL_DAC_CLOCK_SEL                       (volatile uint32_t*)(0x00a0d0a8)

#define CONTROL_DAC_CLOCK_OS_SEL                      (0x000000a8)

#define CONTROL_DAC_CLOCK_RESET_SEL                   (0x0)

// Bit 0           reg_dac_960m_sel               U     RW        default = 'h0
typedef union CONTROL_DAC_CLOCK_SEL_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_dac_960m_sel : 1;
    unsigned int rsvd_0 : 31;
  } b;
} CONTROL_DAC_CLOCK_SEL_FIELD_T;

#define CONTROL_TEST_CLOCK                        (0x00a0d0c4)

#define P_CONTROL_TEST_CLOCK                      (volatile uint32_t*)(0x00a0d0c4)

#define CONTROL_TEST_CLOCK_OS                     (0x000000c4)

#define CONTROL_TEST_CLOCK_RESET                  (0x1c30280)

// Bit 11  :4      reg_dig_timebase               U     RW        default = 'h28
// Bit 12          reg_cntl_tst_clk_oen           U     RW        default = 'h0
// Bit 26  :16     reg_cntl_tst_clk               U     RW        default = 'h1c3
typedef union CONTROL_TEST_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int rsvd_0 : 4;
    unsigned int reg_dig_timebase : 8;
    unsigned int reg_cntl_tst_clk_oen : 1;
    unsigned int rsvd_1 : 3;
    unsigned int reg_cntl_tst_clk : 11;
    unsigned int rsvd_2 : 5;
  } b;
} CONTROL_TEST_CLOCK_FIELD_T;

#define MAC_TIME_O_0                              (0x00a0d0dc)

#define P_MAC_TIME_O_0                            (volatile uint32_t*)(0x00a0d0dc)

#define MAC_TIME_O_0_OS                           (0x000000dc)

#define MAC_TIME_O_0_RESET                        (0x0)

// Bit 31  :0      mac_time_o_0                   U     RO        default = 'h0
typedef union MAC_TIME_O_0_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int mac_time_o_0 : 32;
  } b;
} MAC_TIME_O_0_FIELD_T;

#define MAC_TIME_O_1                              (0x00a0d0e0)

#define P_MAC_TIME_O_1                            (volatile uint32_t*)(0x00a0d0e0)

#define MAC_TIME_O_1_OS                           (0x000000e0)

#define MAC_TIME_O_1_RESET                        (0x0)

// Bit 31  :0      mac_time_o_1                   U     RO        default = 'h0
typedef union MAC_TIME_O_1_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int mac_time_o_1 : 32;
  } b;
} MAC_TIME_O_1_FIELD_T;

#define RAMSHARE_AND_AHB_CTRL                     (0x00a0d0e4)

#define P_RAMSHARE_AND_AHB_CTRL                   (volatile uint32_t*)(0x00a0d0e4)

#define RAMSHARE_AND_AHB_CTRL_OS                  (0x000000e4)

#define RAMSHARE_AND_AHB_CTRL_RESET               (0x7f)

// Bit 7   :0      reg_ahbbus_pause_sel           U     RW        default = 'h7f
// Bit 31  :24     reg_capture_data_mask          U     RW        default = 'h0
typedef union RAMSHARE_AND_AHB_CTRL_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ahbbus_pause_sel : 8;
    unsigned int rsvd_0 : 16;
    unsigned int reg_capture_data_mask : 8;
  } b;
} RAMSHARE_AND_AHB_CTRL_FIELD_T;

#define WATCHDOG_CNTL                             (0x00a0d0ec)

#define P_WATCHDOG_CNTL                           (volatile uint32_t*)(0x00a0d0ec)

#define WATCHDOG_CNTL_OS                          (0x000000ec)

#define WATCHDOG_CNTL_RESET                       (0x0)

// Bit 15  :0      watchdog_tcnt                  U     RW        default = 'h0
// Bit 17          watchdog_sim                   U     RW        default = 'h0
// Bit 18          watchdog_irq_only              U     RW        default = 'h0
// Bit 19          watchdog_en                    U     RW        default = 'h0
// Bit 31          watchdog_reset_n               U     RW        default = 'h0
typedef union WATCHDOG_CNTL_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int watchdog_tcnt : 16;
    unsigned int rsvd_0 : 1;
    unsigned int watchdog_sim : 1;
    unsigned int watchdog_irq_only : 1;
    unsigned int watchdog_en : 1;
    unsigned int rsvd_1 : 11;
    unsigned int watchdog_reset_n : 1;
  } b;
} WATCHDOG_CNTL_FIELD_T;

#define WATCHDOG_COUNT                            (0x00a0d0f0)

#define P_WATCHDOG_COUNT                          (volatile uint32_t*)(0x00a0d0f0)

#define WATCHDOG_COUNT_OS                         (0x000000f0)

#define WATCHDOG_COUNT_RESET                      (0x0)

// Bit 31  :0      watchdog_count                 U     RO        default = 'h0
typedef union WATCHDOG_COUNT_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int watchdog_count : 32;
  } b;
} WATCHDOG_COUNT_FIELD_T;

#define MAC_TIME_O_LATCH                          (0x00a0d0f8)

#define P_MAC_TIME_O_LATCH                        (volatile uint32_t*)(0x00a0d0f8)

#define MAC_TIME_O_LATCH_OS                       (0x000000f8)

#define MAC_TIME_O_LATCH_RESET                    (0x0)

// Bit 31  :0      mac_time_o_latch               U     RO        default = 'h0
typedef union MAC_TIME_O_LATCH_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int mac_time_o_latch : 32;
  } b;
} MAC_TIME_O_LATCH_FIELD_T;

#define MAC_TIME_O_2                              (0x00a0d0fc)

#define P_MAC_TIME_O_2                            (volatile uint32_t*)(0x00a0d0fc)

#define MAC_TIME_O_2_OS                           (0x000000fc)

#define MAC_TIME_O_2_RESET                        (0x0)

// Bit 31  :0      mac_time_o_2                   U     RO        default = 'h0
typedef union MAC_TIME_O_2_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int mac_time_o_2 : 32;
  } b;
} MAC_TIME_O_2_FIELD_T;

#define SRAM_CFG                                  (0x00a0d100)

#define P_SRAM_CFG                                (volatile uint32_t*)(0x00a0d100)

#define SRAM_CFG_OS                               (0x00000100)

#define SRAM_CFG_RESET                            (0x37373737)

// Bit 6   :0      reg_phy_ema_cfg                U     RW        default = 'h37
// Bit 14  :8      reg_fec_ema_cfg                U     RW        default = 'h37
// Bit 22  :16     reg_mac_ema_cfg                U     RW        default = 'h37
// Bit 30  :24     reg_cpu_ema_cfg                U     RW        default = 'h37
typedef union SRAM_CFG_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_phy_ema_cfg : 7;
    unsigned int rsvd_0 : 1;
    unsigned int reg_fec_ema_cfg : 7;
    unsigned int rsvd_1 : 1;
    unsigned int reg_mac_ema_cfg : 7;
    unsigned int rsvd_2 : 1;
    unsigned int reg_cpu_ema_cfg : 7;
    unsigned int rsvd_3 : 1;
  } b;
} SRAM_CFG_FIELD_T;

#define SHARE_RAM_CFG                             (0x00a0d104)

#define P_SHARE_RAM_CFG                           (volatile uint32_t*)(0x00a0d104)

#define SHARE_RAM_CFG_OS                          (0x00000104)

#define SHARE_RAM_CFG_RESET                       (0x10)

// Bit 5   :0      reg_shareram_ema_cfg           U     RW        default = 'h10
typedef union SHARE_RAM_CFG_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_shareram_ema_cfg : 6;
    unsigned int rsvd_0 : 26;
  } b;
} SHARE_RAM_CFG_FIELD_T;

#define AHB_BRIDGE_RST_CFG                       (0x00a0d108)

#define P_AHB_BRIDGE_RST_CFG                     (volatile uint32_t*)(0x00a0d108)

#define AHB_BRIDGE_RST_CFG_OS                    (0x00000108)

#define AHB_BRIDGE_RST_CFG_RESET                 (0x0)

// Bit 7   :0      reg_ahb_bridge_rst_cfg         U     RW        default = 'h0
typedef union AHB_BRIDGE_RST_CFG_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ahb_bridge_rst_cfg : 8;
    unsigned int rsvd_0 : 24;
  } b;
} AHB_BRIDGE_RST_CFG_FIELD_T;

#define CONTROL_RING_OSC                          (0x00a0d10c)

#define P_CONTROL_RING_OSC                        (volatile uint32_t*)(0x00a0d10c)

#define CONTROL_RING_OSC_OS                       (0x0000010c)

#define CONTROL_RING_OSC_RESET                    (0x0)

// Bit 0           reg_ring_osc_enable            U     RW        default = 'h0
// Bit 1           reg_ring_osc_reset_n           U     RW        default = 'h0
// Bit 2           reg_ring_osc_freq_sel          U     RW        default = 'h0
typedef union CONTROL_RING_OSC_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_ring_osc_enable : 1;
    unsigned int reg_ring_osc_reset_n : 1;
    unsigned int reg_ring_osc_freq_sel : 1;
    unsigned int rsvd_0 : 29;
  } b;
} CONTROL_RING_OSC_FIELD_T;

#define CONTROL_BBP_CLOCK                         (0x00a0d110)

#define P_CONTROL_BBP_CLOCK                       (volatile uint32_t*)(0x00a0d110)

#define CONTROL_BBP_CLOCK_OS                      (0x00000110)

#define CONTROL_BP_CLOCK_RESET                   (0x10001)

// Bit 0           reg_bbp_clk_en                 U     RW        default = 'h1
// Bit 23  :16     reg_bbp_clk_div                U     RW        default = 'h1
typedef union CONTROL_BBP_CLOCK_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int reg_bbp_clk_en : 1;
    unsigned int rsvd_0 : 15;
    unsigned int reg_bbp_clk_div : 8;
    unsigned int rsvd_1 : 8;
  } b;
} CONTROL_BBP_CLOCK_FIELD_T;

#endif

#define WIFI_INTF         (0xa0d000)

#define RG_INTF_WT_CLK (WIFI_INTF + 0x7c)
#define RG_INTF_MACCORE_CLK (WIFI_INTF + 0x80)
/*coverity[bad_macro_redef]*/
#define RG_INTF_MPIF_CLK (WIFI_INTF + 0x84)
#define RG_INTF_LDPCRX_CLK (WIFI_INTF + 0x88)
#define RG_INTF_VTB_CLK (WIFI_INTF + 0x8c)

#define RG_INTF_CTRL_CLK (WIFI_INTF + 0xb0)
/*coverity[bad_macro_redef]*/
#define RG_INTF_CPU_CLK (WIFI_INTF + 0x090)
#define RG_INTF_APB_CLK (WIFI_INTF + 0x094)
#define RG_INTF_MAC_CLK (WIFI_INTF + 0x098)
#define RG_INTF_DAC_CLK (WIFI_INTF + 0x0a0)
#define RG_INTF_ADC_CLK (WIFI_INTF + 0x0a4)
#define RG_INTF_VIT_CLK (WIFI_INTF + 0x0ac)
#define RG_INTF_11BRX_CLK (WIFI_INTF + 0x0bc)
#define RG_INTF_320M_CLK (WIFI_INTF + 0x100)
#define RG_INTF_240M_CLK (WIFI_INTF + 0x104)
#define RG_INTF_BTCPU_CLK (WIFI_INTF + 0x108)
#define RG_INTF_BTMAC_CLK (WIFI_INTF + 0x10c)
#define RG_INTF_LDPC_CLK (WIFI_INTF + 0x118)
#define RG_INTF_PIN_MUX_REG1 (WIFI_INTF + 0x004)
#define RG_INTF_SHARE_64K_CAP (WIFI_INTF + 0x0e4)
#define RG_INTF_A42 (WIFI_INTF + 0x0a8)
#define RG_INTF_RTC_CLK_CTRL (WIFI_INTF + 0xc0)
#define RG_INTF_MAC_TIMER_CTRL1 (WIFI_INTF + 0xd0)

#define RG_PMU_A24                                (WIFI_INTF + 0x28)
// Bit 31  :0      rg_ram_pd_shutdown_hw          U     RW        default = 'h0
typedef union RG_PMU_A24_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int rg_ram_pd_shutdown_hw : 32;
  } b;
} RG_PMU_A24_FIELD_T;

#define RG_PMU_A25                                (WIFI_INTF + 0x2c)
// Bit 31  :0      rg_ram_pd_disb_gate_hw         U     RW        default = 'h0
typedef union RG_PMU_A25_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int rg_ram_pd_disb_gate_hw : 32;
  } b;
} RG_PMU_A25_FIELD_T;

#define RG_PMU_A20                                (WIFI_INTF + 0x30)
// Bit 31  :0      rg_ram_pd_shutdown_sw          U     RW        default = 'h0
typedef union RG_PMU_A20_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int rg_ram_pd_shutdown_sw : 32;
  } b;
} RG_PMU_A20_FIELD_T;

#define RG_PMU_A21                                (WIFI_INTF + 0x34)
// Bit 31  :0      rg_ram_pd_disb_gate_sw         U     RW        default = 'h0
typedef union RG_PMU_A21_FIELD
{
  unsigned int data;
  struct
  {
    unsigned int rg_ram_pd_disb_gate_sw : 32;
  } b;
} RG_PMU_A21_FIELD_T;

#endif
